commonLabels:
  addonmanager.kubernetes.io/mode: "Reconcile"

kubeProxyReplacement: true
k8sServiceHost: 192.168.2.9
k8sServicePort: 443

cni:
  install: false
  customConf: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - "172.17.0.0/22"

encryption:
  enabled: true
  type: wireguard

hostFirewall:
  enabled: true
 
# TODO: install certmanager
# or figure out how to use the certmanager
# already running on the nodes
clustermesh:
  apiserver:
    tls:
      auto:
        method: cronJob

hubble:
  tls:
    auto:
      method: cronJob
